/**
 * Position Interface
 *
 * Defines the contract for all position implementations.
 * Positions represent user liquidity positions in DeFi protocols.
 */

import type { TokenInterface } from '../token/index.js';
import type { PoolInterface } from '../pool/index.js';
import type { PositionProtocol, PositionType, PnLSimulationResult } from './position.types.js';

/**
 * PositionInterface
 *
 * Common interface for all position types across protocols.
 * Concrete implementations (UniswapV3Position, etc.) extend BasePosition
 * which implements this interface.
 */
export interface PositionInterface {
  /**
   * Unique identifier (cuid)
   * Generated by database on creation
   */
  readonly id: string;

  /**
   * Protocol-specific composite key
   * For UniswapV3: "uniswapv3/{chainId}/{nftId}"
   */
  readonly positionHash: string;

  /**
   * User who owns this position
   */
  readonly userId: string;

  /**
   * Protocol identifier
   * @example 'uniswapv3'
   */
  readonly protocol: PositionProtocol;

  /**
   * Position type classification
   * @example 'LP_CONCENTRATED'
   */
  readonly type: PositionType;

  /**
   * Token0 of the position's pool
   */
  readonly token0: TokenInterface;

  /**
   * Token1 of the position's pool
   */
  readonly token1: TokenInterface;

  /**
   * Virtual pool object constructed from position data.
   * Provides backward compatibility for code that accesses pool.config, pool.state, etc.
   */
  readonly pool: PoolInterface;

  // ============================================================================
  // PnL Fields (all in quote token units)
  // ============================================================================

  /**
   * Current value of the position in quote token units
   */
  readonly currentValue: bigint;

  /**
   * Cost basis (total invested) in quote token units
   */
  readonly costBasis: bigint;

  /**
   * Realized PnL from position changes
   */
  readonly realizedPnl: bigint;

  /**
   * Unrealized PnL (mark-to-market)
   */
  readonly unrealizedPnl: bigint;

  /**
   * Realized cashflow (for non-AMM protocols like perpetuals)
   */
  readonly realizedCashflow: bigint;

  /**
   * Unrealized cashflow (accrued but not claimed)
   */
  readonly unrealizedCashflow: bigint;

  // ============================================================================
  // Yield Fields
  // ============================================================================

  /**
   * Total yield collected over position lifetime
   */
  readonly collectedYield: bigint;

  /**
   * Unclaimed yield (available to collect)
   */
  readonly unclaimedYield: bigint;

  /**
   * Timestamp of last yield claim
   */
  readonly lastYieldClaimedAt: Date;

  // ============================================================================
  // APR Fields
  // ============================================================================

  /**
   * Base APR (fee/yield APR), null if not calculated
   */
  readonly baseApr: number | null;

  /**
   * Reward APR (incentive programs), null if not applicable
   */
  readonly rewardApr: number | null;

  /**
   * Total APR (baseApr + rewardApr), null if not calculated
   */
  readonly totalApr: number | null;

  // ============================================================================
  // Lifecycle
  // ============================================================================

  /**
   * When the position was opened
   */
  readonly positionOpenedAt: Date;

  /**
   * When the position was closed (null if still open)
   */
  readonly positionClosedAt: Date | null;

  /**
   * Whether the position is currently active
   */
  readonly isActive: boolean;

  // ============================================================================
  // Protocol-specific (generic Record for interface)
  // ============================================================================

  /**
   * Protocol-specific configuration
   * For type-safe access, use typedConfig on concrete class
   */
  readonly config: Record<string, unknown>;

  /**
   * Protocol-specific state
   * For type-safe access, use typedState on concrete class
   */
  readonly state: Record<string, unknown>;

  // ============================================================================
  // Timestamps
  // ============================================================================

  readonly createdAt: Date;
  readonly updatedAt: Date;

  // ============================================================================
  // Methods
  // ============================================================================


  /**
   * Get total realized PnL including cashflow
   */
  getTotalRealizedPnl(): bigint;

  /**
   * Get total unrealized PnL including accrued cashflow
   */
  getTotalUnrealizedPnl(): bigint;

  /**
   * Simulate the position at a given price.
   * Used for interactive PnL curve visualization.
   *
   * @param price - The base token price in quote token units (scaled by quote token decimals)
   * @returns Full simulation result including value, PnL, and percent
   */
  simulatePnLAtPrice(price: bigint): PnLSimulationResult;
}
