/**
 * Position Interface
 *
 * Defines the contract for all position implementations.
 * Positions represent user liquidity positions in DeFi protocols.
 */

import type { Erc20Token } from '../token/index.js';
import type { UniswapV3Pool } from '../pool/index.js';
import type { PositionProtocol, PositionType, PositionJSON } from './position.types.js';

/**
 * PositionInterface
 *
 * Common interface for all position types across protocols.
 * Concrete implementations (UniswapV3Position, etc.) extend BasePosition
 * which implements this interface.
 */
export interface PositionInterface {
  /**
   * Unique identifier (cuid)
   * Generated by database on creation
   */
  readonly id: string;

  /**
   * Protocol-specific composite key
   * For UniswapV3: "uniswapv3/{chainId}/{nftId}"
   */
  readonly positionHash: string;

  /**
   * User who owns this position
   */
  readonly userId: string;

  /**
   * Protocol identifier
   * @example 'uniswapv3'
   */
  readonly protocol: PositionProtocol;

  /**
   * Position type (concentrated liquidity, etc.)
   * @example 'CL_TICKS'
   */
  readonly positionType: PositionType;

  /**
   * Pool reference (full object for token access)
   */
  readonly pool: UniswapV3Pool;

  /**
   * Whether token0 is the quote token
   * If true: token0 = quote, token1 = base
   * If false: token0 = base, token1 = quote
   */
  readonly isToken0Quote: boolean;

  // ============================================================================
  // PnL Fields (all in quote token units)
  // ============================================================================

  /**
   * Current value of the position in quote token units
   */
  readonly currentValue: bigint;

  /**
   * Current cost basis (total invested) in quote token units
   */
  readonly currentCostBasis: bigint;

  /**
   * Realized PnL from position changes
   */
  readonly realizedPnl: bigint;

  /**
   * Unrealized PnL (mark-to-market)
   */
  readonly unrealizedPnl: bigint;

  /**
   * Realized cashflow (for non-AMM protocols like perpetuals)
   */
  readonly realizedCashflow: bigint;

  /**
   * Unrealized cashflow (accrued but not claimed)
   */
  readonly unrealizedCashflow: bigint;

  // ============================================================================
  // Fee Fields
  // ============================================================================

  /**
   * Total fees collected over position lifetime
   */
  readonly collectedFees: bigint;

  /**
   * Unclaimed fees (available to collect)
   */
  readonly unClaimedFees: bigint;

  /**
   * Timestamp of last fee collection
   */
  readonly lastFeesCollectedAt: Date;

  /**
   * Calculated total APR (null if not calculated)
   */
  readonly totalApr: number | null;

  // ============================================================================
  // Price Range
  // ============================================================================

  /**
   * Lower price bound (quote per base token)
   */
  readonly priceRangeLower: bigint;

  /**
   * Upper price bound (quote per base token)
   */
  readonly priceRangeUpper: bigint;

  // ============================================================================
  // Lifecycle
  // ============================================================================

  /**
   * When the position was opened
   */
  readonly positionOpenedAt: Date;

  /**
   * When the position was closed (null if still open)
   */
  readonly positionClosedAt: Date | null;

  /**
   * Whether the position is currently active
   */
  readonly isActive: boolean;

  // ============================================================================
  // Protocol-specific (generic Record for interface)
  // ============================================================================

  /**
   * Protocol-specific configuration
   * For type-safe access, use typedConfig on concrete class
   */
  readonly config: Record<string, unknown>;

  /**
   * Protocol-specific state
   * For type-safe access, use typedState on concrete class
   */
  readonly state: Record<string, unknown>;

  // ============================================================================
  // Timestamps
  // ============================================================================

  readonly createdAt: Date;
  readonly updatedAt: Date;

  // ============================================================================
  // Methods
  // ============================================================================

  /**
   * Serialize position to JSON format for API responses.
   * Converts Date objects to ISO strings and bigint to strings.
   */
  toJSON(): PositionJSON;

  /**
   * Get the base token (the token with price risk exposure)
   */
  getBaseToken(): Erc20Token;

  /**
   * Get the quote token (the reference/numeraire token)
   */
  getQuoteToken(): Erc20Token;

  /**
   * Get total realized PnL including cashflow
   */
  getTotalRealizedPnl(): bigint;

  /**
   * Get total unrealized PnL including accrued cashflow
   */
  getTotalUnrealizedPnl(): bigint;

  /**
   * Simulate the position's PnL at a given price.
   * Used for interactive PnL curve visualization.
   *
   * @param price - The base token price in quote token units (scaled by quote token decimals)
   * @returns The simulated PnL at the given price in quote token units
   */
  simulatePnLAtPrice(price: bigint): bigint;
}
