/**
 * PoolPrice Interface
 *
 * Defines the contract for all pool price implementations.
 * Pool prices represent historic price snapshots for pools.
 */

import type { PoolPriceProtocol, PoolPriceJSON } from './pool-price.types.js';

/**
 * PoolPriceInterface
 *
 * Common interface for all pool price types across protocols.
 * Concrete implementations (UniswapV3PoolPrice, etc.) extend BasePoolPrice
 * which implements this interface.
 */
export interface PoolPriceInterface {
  /**
   * Unique identifier (cuid)
   * Generated by database on creation
   */
  readonly id: string;

  /**
   * Protocol identifier
   * Identifies which DEX protocol this price belongs to
   * @example 'uniswapv3'
   */
  readonly protocol: PoolPriceProtocol;

  /**
   * Foreign key to Pool.id
   * References the pool this price snapshot belongs to
   */
  readonly poolId: string;

  /**
   * When price was recorded (blockchain timestamp)
   * For EVM chains, this is the block timestamp
   */
  readonly timestamp: Date;

  /**
   * Price of token1 in terms of token0
   * Stored as bigint for precision (smallest token units)
   * @example 1000000000000000000n = 1 token1 per token0
   */
  readonly token1PricePerToken0: bigint;

  /**
   * Price of token0 in terms of token1
   * Stored as bigint for precision (smallest token units)
   */
  readonly token0PricePerToken1: bigint;

  /**
   * Protocol-specific configuration (as generic Record)
   * For type-safe access, use typedConfig on concrete class
   */
  readonly config: Record<string, unknown>;

  /**
   * Protocol-specific state at snapshot time (as generic Record)
   * For type-safe access, use typedState on concrete class
   */
  readonly state: Record<string, unknown>;

  /**
   * Timestamp when record was created in database
   */
  readonly createdAt: Date;

  /**
   * Timestamp when record was last updated
   */
  readonly updatedAt: Date;

  /**
   * Serialize pool price to JSON format for API responses.
   * Converts Date objects to ISO strings.
   * Converts bigint values to strings.
   */
  toJSON(): PoolPriceJSON;
}
