/**
 * Pool Interface
 *
 * Defines the contract for all pool implementations.
 * Pools represent liquidity pool positions across different DEX protocols.
 */

import type { Erc20Token } from '../token/index.js';
import type { Protocol, PoolType, PoolJSON } from './pool.types.js';

/**
 * PoolInterface
 *
 * Common interface for all pool types across protocols.
 * Concrete implementations (UniswapV3Pool, etc.) extend BasePool
 * which implements this interface.
 */
export interface PoolInterface {
  /**
   * Unique identifier (cuid)
   * Generated by database on creation
   */
  readonly id: string;

  /**
   * Protocol identifier
   * Identifies which DEX protocol this pool belongs to
   * @example 'uniswapv3'
   */
  readonly protocol: Protocol;

  /**
   * Pool type identifier
   * Identifies the pool mechanism (concentrated liquidity, constant product, etc.)
   * @example 'CL_TICKS'
   */
  readonly poolType: PoolType;

  /**
   * First token in the pair
   * Full Erc20Token object with type-safe config access
   * By convention, token0 < token1 (by address comparison)
   */
  readonly token0: Erc20Token;

  /**
   * Second token in the pair
   * Full Erc20Token object with type-safe config access
   * By convention, token1 > token0 (by address comparison)
   */
  readonly token1: Erc20Token;

  /**
   * Fee tier in basis points
   * @example 500 = 0.05%, 3000 = 0.3%, 10000 = 1%
   */
  readonly feeBps: number;

  /**
   * Protocol-specific configuration (as generic Record)
   * For type-safe access, use typedConfig on concrete class
   */
  readonly config: Record<string, unknown>;

  /**
   * Protocol-specific mutable state (as generic Record)
   * For type-safe access, use typedState on concrete class
   */
  readonly state: Record<string, unknown>;

  /**
   * Timestamp when pool was created in database
   */
  readonly createdAt: Date;

  /**
   * Timestamp when pool was last updated
   */
  readonly updatedAt: Date;

  /**
   * Serialize pool to JSON format for API responses.
   * Converts Date objects to ISO strings.
   * Includes serialized token0 and token1.
   */
  toJSON(): PoolJSON;

  /**
   * Get a human-readable display name for the pool.
   * @returns "TOKEN0/TOKEN1 (fee%)" format
   */
  getDisplayName(): string;
}
