/**
 * Pool Interface
 *
 * Defines the contract for all pool implementations.
 * Pools represent liquidity pool positions across different DEX protocols.
 */

import type { TokenInterface } from '../token/index.js';
import type { Protocol, PoolJSON } from './pool.types.js';

/**
 * PoolInterface
 *
 * Common interface for all pool types across protocols.
 * Concrete implementations (UniswapV3Pool, etc.) extend BasePool
 * which implements this interface.
 */
export interface PoolInterface {
  /**
   * Unique identifier (cuid)
   * Generated by database on creation
   */
  readonly id: string;

  /**
   * Protocol identifier
   * Identifies which DEX protocol this pool belongs to
   * @example 'uniswapv3'
   */
  readonly protocol: Protocol;

  /**
   * First token in the pair
   * Concrete type depends on protocol (Erc20Token for EVM, SPL token for Solana, etc.)
   */
  readonly token0: TokenInterface;

  /**
   * Second token in the pair
   * Concrete type depends on protocol (Erc20Token for EVM, SPL token for Solana, etc.)
   */
  readonly token1: TokenInterface;

  /**
   * Protocol-specific configuration (as generic Record)
   * For type-safe access, use typedConfig on concrete class
   */
  readonly config: Record<string, unknown>;

  /**
   * Protocol-specific mutable state (as generic Record)
   * For type-safe access, use typedState on concrete class
   */
  readonly state: Record<string, unknown>;

  /**
   * Timestamp when pool was created in database
   */
  readonly createdAt: Date;

  /**
   * Timestamp when pool was last updated
   */
  readonly updatedAt: Date;

  /**
   * Serialize pool to JSON format for API responses.
   * Converts Date objects to ISO strings.
   * Includes serialized token0 and token1.
   */
  toJSON(): PoolJSON;

  /**
   * Get a human-readable display name for the pool.
   * @returns "TOKEN0/TOKEN1 (fee%)" format
   */
  getDisplayName(): string;
}
